### ISSUE TITLE
Write section on securely clearing memory in C/C++ and undefined behaviour.

### ISSUE THREAD

**Issue by kbeyls** [llsoftsec/llsoftsecbook#183]
see TODO in book.

**Comment by kbeyls** [comment]
The upcoming [Silent Bugs Matter: A Study of Compiler-Introduced Security Bugs](https://www.usenix.org/conference/usenixsecurity23/presentation/xujianhao) publication at USENIX'32, first author @H0w1, presents an analysis of how optimizing compilers can generate security vulnerabilities in binary code where that security vulnerability is not present in the source code.
At first sight, it seems that a summary of the insights in that paper could be a good section for the book.

Securely clearing memory is just one of the types of issues of a more general class of so-called Compiler-Introduced Security Bugs (CISB).

**Comment by lucic71** [comment]
Hi,

Also the examples in [Undefined Behavior: What Happened to My Code?](https://cs.stanford.edu/~zhihao/papers/apsys12.pdf) would make very good candidates for a section about the security vulnerabilities introduced by compiler optimizations.

**Comment by kbeyls** [comment]
> Hi,
> 
> Also the examples in [Undefined Behavior: What Happened to My Code?](https://cs.stanford.edu/~zhihao/papers/apsys12.pdf) would make very good candidates for a section about the security vulnerabilities introduced by compiler optimizations.

Thank you very much for sharing that paper @lucic71 ! It does look like the examples in that paper are good candidates indeed to describe in such a section in the book.

@all-contributors please add @lucic71  for bugs, ideas

**Comment by lucic71** [comment]
@kbeyls I have some drafts for a section covering the security vulnerabilities introduced by compilers, I will open a PR in the following days with that if that's ok with you.

**Comment by kbeyls** [comment]
> @kbeyls I have some drafts for a section covering the security vulnerabilities introduced by compilers, I will open a PR in the following days with that if that's ok with you.

That is absolutely awesome! I am looking forward to the PR!

**Comment by kbeyls** [comment]
I believe this issue has been fixed by #200.
There is probably more that could and should be written about how undefined behavior results in compiler-introduced security vulnerabilities, but that can be tracked under a separate issue.
