### ISSUE TITLE
Make HTML version of book mobile device friendly.

### ISSUE THREAD

**Issue by g-kouv** [llsoftsec/llsoftsecbook#32]
The HTML version of the book here: https://llsoftsec.github.io/llsoftsecbook/ should be made easier to read on mobile devices.

**Comment by JLouisKaplan-Arm** [comment]
I haven't much CSS knowledge, but something like this might be enough as a temporary stop-gap?
https://github.com/JLouisKaplan-Arm/llsoftsecbook/blob/gh-pages/responsive_small.css

the effects of which can be seen (with width less than 768px) at:
https://jlouiskaplan-arm.github.io/llsoftsecbook/

The text justification needs a little further tweaking.

**Comment by kbeyls** [comment]
I like it :)
When I tried it on my mobile phone, the look-and-feel was as I expected, i.e. making the book readable.

@g-kouv , I wonder what you think?

**Comment by JLouisKaplan-Arm** [comment]
_small update:_ returned headings to being left aligned, and only justified <p> elements, which looks a little neater to my eyes (no big gaps in words of headings).

**Comment by kbeyls** [comment]
I've been looking for examples in the past few days of style sheets used in other online books written using pandoc.
I only found 2 categories:
1. https://jez.io/tufte-pandoc-css/ (source code at https://github.com/jez/tufte-pandoc-css)
2. The books written using bookdown, see examples at https://bookdown.org/.

Both categories seem to have style sheets that are "responsive", i.e. adapt well to different screen sizes, such as mobile or desktop.

For tufte-pandoc-css, I particularly like:
* Footnotes appear as side notes in the html rendering.
* The example at https://jez.io/tufte-pandoc-css/ doesn't show it, but it is possible to have the table of contents as side notes.
* I just personally like the overall look-and-feel.

* A disadvantage is that it seems that the license the CSS file is under may be incompatible with the CC-BY license used for llsoftsecbook.

For the examples at https://bookdown.org/, I liked:
* It makes use of bootstrap, which should make it easier to adapt/tweak it further.

I like the overall look-and-feel less though - it seems there are more buttons etc - making the books feel more like a website than a "book". Of course, this is very subjective.

Overall, I think that maybe the best thing to do is to just bite the bullet and start writing our own CSS.

**Comment by kbeyls** [comment]
I think we can close this issue now.
The HTML version of the book is now as good (or as bad) as the large-screen version.
We can drive further improvements to the HTML output (both for mobile and large-screen versions) through #130
