### ISSUE TITLE
Hyphenate "low-level"

### ISSUE THREAD

**Issue by sam-ellis** [llsoftsec/llsoftsecbook#50]
Would recommend to change instances of "low level" to hyphenated form "low-level", the later being commonly recognized (e.g. see https://www.merriam-webster.com/dictionary/low-level).

**Comment by kbeyls** [comment]
A few more examples of "low-level" being spelled with a hyphen:
- https://en.wikipedia.org/wiki/High-_and_low-level
- https://dictionary.cambridge.org/dictionary/english/low-level
- https://www.macmillandictionary.com/dictionary/american/low-level

In summary, it seems there is consensus using a hyphen is the right way to spell low-level.

Thanks for reporting this @sam-ellis
