### ISSUE TITLE
Make headings and subheadings directly linkable

### ISSUE THREAD

**Issue by JLouisKaplan-Arm** [llsoftsec/llsoftsecbook#64]
As the book gets bigger, it will likely become increasingly useful to be able to link directly to headings and subheadings (both externally, and crosslinking from book itself). Maybe Pandoc has a setting to enable this?

**Comment by kbeyls** [comment]
The HTML version (e.g. as published on https://llsoftsec.github.io/llsoftsecbook/) does have anchors for all the headings already; for example: https://llsoftsec.github.io/llsoftsecbook/#hardware-support-for-protection-against-memory-vulnerabilities

So, I'd say, this is already present?
Maybe, however, what you're after is somehow make it more obvious what those anchors/URLs are and/or make them easier to copy paste somehow?

**Comment by JLouisKaplan-Arm** [comment]
Ah yes you are right. I think we are half-way there already but it can be convenient to actually turn the headers into links to their own HTML tag IDs. For example, in the Rust book you can click on the headers and your address bar updates with the more specific URL:

https://doc.rust-lang.org/book/ch03-03-how-functions-work.html#function-bodies-contain-statements-and-expressions

There is definitely precedent for _not_ enabling the above (e.g. Wikipedia headings are not clickable) but I often find it extremely convenient.

**Comment by kbeyls** [comment]
I agree it makes a lot of sense.
After quickly looking for what pandoc can do, it seems this needs a custom (lua) script to implement this, see https://github.com/jgm/pandoc/issues/2723.
So, I'm definitely in favour of implementing this.
Not sure if anyone here is already fluent with implementing pandoc lua script filters?

**Comment by JLouisKaplan-Arm** [comment]
I have some hack-day time I could use to try and do this over the next week or two if you'd like.

If you think it's OK to add a bit of javascript to the page, I would be tempted to try and do it the javascript way as I know a little more JS than Lua (which I have no experience in), and the last comment on that pandocs issue (from pandocs creator John McFarlane) suggests it might be a good approach. No preference though :)

**Comment by kbeyls** [comment]
Thanks for offering to implement this @JLouisKaplan-Arm , that'd be awesome!

I think it may have value to avoid using javascript, as I imagine that some potential readers do turn off javascript by default in their browsers. That being said, the loss of functionality is probably minor if javascript is turned off; if it's being used just for this feature.

If it was me, I'd probably spend a little bit of time exploring lua filters in pandoc, as I'd expect that we may want to use lua filters for other functionality in the future too. But if it would prove to be too hard to implement, javascript will do for this feature.

**Comment by JLouisKaplan-Arm** [comment]
> I'd probably spend a little bit of time exploring lua filters in pandoc, as I'd expect that we may want to use lua filters for other functionality in the future too

Sounds good to me - I'll give that a try. As someone who disables by JS by default I can certainly see your point :)
