### ISSUE TITLE
Docker output for local builds belongs to `root`

### ISSUE THREAD

**Issue by JLouisKaplan-Arm** [llsoftsec/llsoftsecbook#84]
When using the `build_with_docker.sh` script for local builds, the output files belong to the `root` user and group because this is the user that is active by default in the Docker container itself when building. This isn't ideal if building on a machine where a user doesn't have `sudo` access, as the output files can't be removed or modified.

I have a rough idea for a fix that may/may not work (essentially, ensure a user is created in the container that matches the user that triggers the build script, and make sure all the Docker-internal build scripts are run with this user active). Happy to have a go at it if you'd like.

**Comment by sam-ellis** [comment]
Yes please, a pull request would be great. Happy to try it out / review.

**Comment by JLouisKaplan-Arm** [comment]
I think the merged PR has addressed this issue. Closing for now.
